DOC   = dokumentace


doc: $(DOC).tex
	pdflatex $(DOC)
	pdflatex $(DOC)


clean:
	rm -f $(DOC).aux
	rm -f $(DOC).log
	rm -f $(DOC).dvi
	rm -f $(DOC).ps
	rm -f $(DOC).pdf
	rm -f $(DOC).bbl
	rm -f $(DOC).blg
	rm -f $(DOC).out
